# Site settings
title: Anupam Chowdhury
general_email: anupamc24@outlook.com
academic_email: ttz178473@iitd.ac.in

description: > # this means to ignore newlines until "baseurl:"
  Dedicated Ph.D. student specializing in Textile and Fibre Engineering at the Indian Institute of Technology Delhi. Research focuses on the study of shape memory coupled piezoelectric nanocomposites.


url: cictema.github.io
baseurl: /anupam-portfolio
# baseurl: "/academic-portfolio" # the subpath of your site, e.g. /blog/

url: "" # the base hostname & protocol for your site

linkedin_username: anupamassam
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title